### PR TITLE
fix(exoflex): use width from style for transform and thumb size

### LINKED ISSUE #528: exoflex: Switch
**Describe the bug**
`width` props doesn't actually widen the track, more like scaling it.
Kapture 2020-07-02 at 13 18 00

when setting the width manually from `trackStyle` props, it produce a bug where the thumb doesn't reach the end.
Screen Shot 2020-07-02 at 12 18 24 PM

**To Reproduce**
1. Set `width` to any value, ex. `width={60}`
2. Set width from `trackStyle`, ex. `trackStyle={{ width: 80 }}`

**Expected behavior**
- `width` props should only lengthen the track (or maybe you can change the props name to `size`)
- setting `width` in `trackStyle` should work properly

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS12.4
 - Package version: 3.4.0

### PR DESCRIPTION
**Pull request by oshimayoan**
Fix #528

Kapture 2020-07-06 at 12 11 42

### CODE REVIEW

File: packages/exoflex/src/components/Switch.tsx [hunk 1]
```diff
@@ -51,20 +59,26 @@ export default function Switch(props: SwitchProps) {
...
+        width: thumbSize,
+        height: thumbSize,
+      },
+    ],
   };
 
   let translateXValue = xValue.interpolate({
     inputRange: [0, 1],
-    outputRange: [0, width / 2],
+    outputRange: [0, width - (thumbSize + 2 * MARGIN)],
```
Comment (darcien) [inline packages/exoflex/src/components/Switch.tsx:81]: Nice fix!

File: packages/exoflex/src/components/Switch.tsx [hunk 2]
```diff
@@ -36,8 +37,15 @@ export default function Switch(props: SwitchProps) {
...
+  let width = +(StyleSheet.flatten(trackStyle)?.width || widthProps);
 
-  let thumbSize = width / 2 - 2 * MARGIN;
+  let thumbSize =
+    +(
+      StyleSheet.flatten(themeStyle?.switch?.thumbStyle)?.width ||
+      StyleSheet.flatten(thumbStyle)?.width ||
+      width / 2
+    ) -
+    2 * MARGIN;
```
Comment (darcien) [inline packages/exoflex/src/components/Switch.tsx:48]: Hmmm, the order of precedence looks weird 🤔 

Right now it's `themeStyle > thumbStyle > width`.
I think it should be `thumbStyle > themeStyle > width`, where the `thumbStyle` gets the priority because this is used only for the `thumbSize`.

What do you think?

Whatever we pick, we probably need to add this to the docs though.

**Comment by darcien** [comment]
> Kapture 2020-07-06 at 12 11 42

Haha, I like the custom example, looks like a slider for lazy people 😆

File: packages/exoflex/src/components/Switch.tsx (hunk 2 above)
Comment (oshimayoan) [reply packages/exoflex/src/components/Switch.tsx:48]: Oops, nice catch! Yeah it should be `thumbStyle > themeStyle > width`, I think I pasted it at the wrong position without realizing that it should be the opposite order from the style below.

Comment (oshimayoan) [reply packages/exoflex/src/components/Switch.tsx:48]: > Whatever we pick, we probably need to add this to the docs though.

Absolutely!
